<a href="https://colab.research.google.com/github/hasanzeynal/Tensorflow-Developer-Certificate/blob/main/00_TensorFlow_Fundamentals/dl_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# We are gonna cover some fundamentals of using tensor in Tensorflow.
More specifically:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular python function)
* Using GPU's in tensorflow(or TPU's)
* Exercises

## Introduction to Tensors

In [1]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#create tensors with tf.constant
scalar = tf.constant(11)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [3]:
#check the type of tensor
scalar.dtype

tf.int32

In [4]:
#check the number fo dimentions of tensor
scalar.ndim

0

In [5]:
#creating vector
vector = tf.constant([10,20,30])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [6]:
#check the number of dimension of vector
vector.ndim

1

In [7]:
#create a matrix(has mor than 1 dimension)
matrix = tf.constant([[11,8],
                     [8,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 8, 11]], dtype=int32)>

In [8]:
#check for the number of dimensions
matrix.ndim

2

In [9]:
#create another matrix
another_matrix = tf.constant([[1, 2, 3],
                             [1, 2, 3],
                             [1, 2, 3]],dtype = tf.float16) #specify dtype of tensor
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float16)>

In [10]:
#creating 3 dimensinal matrix
threed_dimen = tf.constant([[[11,8],[1,2]],
                            [[8,11],[1,2]],
                            [[11,2],[1,2]]])
threed_dimen

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[11,  8],
        [ 1,  2]],

       [[ 8, 11],
        [ 1,  2]],

       [[11,  2],
        [ 1,  2]]], dtype=int32)>

In [11]:
#check for the number of dimentions
threed_dimen.ndim

3

In [12]:
#creat 4 dimensinal matrix
four_dimen = tf.constant([[[[1,2,3],[1,2,3]],
                          [[1,2,3],[1,2,3]]],
                          [[[1,2,3],[1,2,3]],
                          [[1,2,3],[1,2,3]]]])
four_dimen

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int32)>

In [13]:
four_dimen.ndim

4

### What we have learned so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: 2 dimensional array
* Tensor: n dimensional array(n can be any number, o dimensinal is a scalar, 1 dimensional is a vector)

### Creating Tensor with tf.Variable()

In [14]:
#create same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([1,2,3,4])
unchangeable_tensor = tf.constant([1,2,3,4])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>)

In [15]:
#Let's try to change changeable_tensor
changeable_tensor[1] = 4
changeable_tensor

TypeError: ignored

In [93]:
#What about .assign()?
changeable_tensor[3].assign(7)
changeable_tensor
#constant doesn't have .assign() function

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 7], dtype=int32)>

### Creating random tensors

In [94]:
#create 2 tensors
tensor_1 = tf.random.Generator.from_seed(45) # set seed for reproducibility
tensor_1 = tensor_1.uniform(shape=(3,2))
tensor_2 = tf.random.Generator.from_seed(45) 
tensor_2 = tensor_2.uniform(shape=(3,2))
tensor_1, tensor_2, tensor_1 == tensor_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.86540747, 0.8862978 ],
        [0.27795732, 0.8857763 ],
        [0.2179842 , 0.29115117]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.86540747, 0.8862978 ],
        [0.27795732, 0.8857763 ],
        [0.2179842 , 0.29115117]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [95]:
#Let's use tf.random.shuffle() to shuffle our tensor
not_shuffled = tf.constant([1,2,3,4,5])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 5, 2, 1, 3], dtype=int32)>

In [96]:
#Let's look at the 2 dimensional tensor
not_shuffled = tf.constant([[1,2,3,4,5],[6,7,8,9,10]])
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled,shuffled

(<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=int32)>)

In [97]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled,seed = 42) # operation level random seed


<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]], dtype=int32)>

### Other Ways to Create Tensors

In [16]:
#create tensor of all ones
tf.ones(shape = (3,6))

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
#create tensor of all zeroes
tf.zeros(shape = (4,5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into Tensors
The main difference between NumPy arrays and TensorFlow Tensors is tensors can run on the GPU(way much faster for numerical computing)

In [18]:
#creating numpy array
import numpy as np
numpy_array = np.arange(1,25,dtype = np.int32) #create NumPy array between 1 and 25
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
#turn into tensor
tensor_1 = tf.constant(numpy_array)
#change shape of tensor
tensor_2 = tf.constant(numpy_array,shape = (2,3,4)) # 2*3*4 = 24
tensor_1,tensor_2

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Getting Information from Tensors.
When dealing with tensors, you probably wanna be aware of following attributes:
* Shape
* Rank
* Axis or Dimension
* Size

In [20]:
#create rank 4 tensor(4 dimensional)
rank4_tensor = tf.ones(shape = (2,2,3,4))
rank4_tensor

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [21]:
#looking for shape,rank and size of rank4_tensor
rank4_tensor.shape,rank4_tensor.ndim,tf.size(rank4_tensor)

(TensorShape([2, 2, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

Let's look at previous example:
* Shape - Shape of Tensor
* Rank - Number of Dimensions
* Size - Total Number of Elements in the Tensor

### Indexing
Tensors can be indexed like Python Lists or NumPy Arrays

In [22]:
# Get the first 2 elements if each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [23]:
#Get the first element from each dimension from each index except final dimension
rank4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>

In [24]:
#create rank 2 tensor
rank_2_tensor = tf.constant([[1,2,3,4,5],[6,7,8,9,10]])
rank_2_tensor

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [25]:
#get the last item of each of row of  our rank tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 10], dtype=int32)>

In [26]:
# add in extra dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 5, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]], dtype=int32)>

In [27]:
#Alternative to the tf.newaxis
tf.expand_dims(rank_2_tensor,axis = -1)

<tf.Tensor: shape=(2, 5, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]], dtype=int32)>

In [28]:
#adding di,ension to the first axis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]], dtype=int32)>

In [29]:
#adding di,ension to the middle
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]], dtype=int32)>

In [30]:
#lookig for some attributes in the tensor
print("The Shape of Tensor:",tf.expand_dims(rank_2_tensor,axis=1).shape)
print("The Number of Dimensions:",tf.expand_dims(rank_2_tensor,axis=1).ndim)
print("The total number of elements:",tf.size(tf.expand_dims(rank_2_tensor,axis=1)))

The Shape of Tensor: (2, 1, 5)
The Number of Dimensions: 3
The total number of elements: tf.Tensor(10, shape=(), dtype=int32)


### Manupulating tensors(tensor operations)
**Basic Operations**





In [31]:
#addition
tensor = tf.constant([[10,20],[30,40]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [32]:
# Original tensor is not changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [33]:
#multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]], dtype=int32)>

In [34]:
#subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 10],
       [20, 30]], dtype=int32)>

### Matrix *Multiplication*

  In machine Learning, Matrix multiplication is one of the most usefull and important operation.
 
  There are 2 rules to multiply our tensors(or matrices):

1. The inner dimensions must match.
2. The resulting matrix has the shape of outher dimensions.

In [35]:
#matrix multiplication in tensowflow
print(tensor)
tf.linalg.matmul(tensor,tensor)

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 700, 1000],
       [1500, 2200]], dtype=int32)>

In [36]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 100,  400],
       [ 900, 1600]], dtype=int32)>

In [37]:
#Task: create tensor with shape of (3,3) and shape of (3,2)
tensor_1 = tf.constant([[1,4,5],
                        [1,2,5],
                        [1,5,9]])

tensor_2 = tf.constant([[1,2],
                        [8,9],
                        [5,6]])

In [38]:
# then multiply them with a Python operation
tensor_1 @ tensor_2 #"@" in Python for the Matrix Multiplication

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 58,  68],
       [ 42,  50],
       [ 86, 101]], dtype=int32)>

In [39]:
#let's do that with tf.matmul
tf.linalg.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 58,  68],
       [ 42,  50],
       [ 86, 101]], dtype=int32)>

In [40]:
#let's create two tensor with the same shape
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7,6],
                [8,9],
                [4,5]])
#let's try to multiply them
X @ y

InvalidArgumentError: ignored

In [41]:
#let's change the shape of y and try again
X @ tf.reshape(y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 14, 18],
       [57, 34, 44],
       [89, 54, 70]], dtype=int32)>

In [42]:
#now,reshape the X and we cann see that works or not
tf.reshape(X,shape = (2,3)) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 39],
       [92, 99]], dtype=int32)>

In [43]:
#Let's see the difference between tf.transpose() and tf,reshape() 
X,tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [44]:
#can do same thing with tf.transpose()
tf.transpose(X) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 58],
       [70, 78]], dtype=int32)>

In [45]:
#transpose y instead of X
tf.linalg.matmul(X,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 26, 14],
       [45, 60, 32],
       [71, 94, 50]], dtype=int32)>

📖 **Resource**: Info and Example of Matrix Multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

### The Dot Product
You can perform matrix multiplication using:

*  `tf.matmul()`
*  `tf.tensordot()`
* `@`





In [46]:
X,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[7, 6],
        [8, 9],
        [4, 5]], dtype=int32)>)

In [47]:
#maltiply with tf.tensordot() on X and y
tf.tensordot(tf.transpose(X),y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 58],
       [70, 78]], dtype=int32)>

In [48]:
tf.tensordot(X,tf.transpose(y),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 26, 14],
       [45, 60, 32],
       [71, 94, 50]], dtype=int32)>



---



---


Generally,when performing matrix multiplication on two tensors and one of them is not fit for the multiplication,you are gonna use transpose (rather than reshape) to get satisfy the rules of Matrix Multiplication.

### Changing datantype of tensor

In [49]:
tf.__version__

'2.12.0'

In [50]:
#create a tensor with type of float
A = tf.constant([1.5,1,9])
A.dtype

tf.float32

In [51]:
B = tf.constant([[1,2,3],[1,2,5]])
B.dtype

tf.int32

In [52]:
#change dtype from float32 to float16(reduce precision)
C = tf.cast(A,dtype = tf.float16)
C.dtype

tf.float16

In [53]:
#change from int32 to float32
E = tf.cast(B,dtype = tf.float32)
B.dtype,E.dtype

(tf.int32, tf.float32)

### Aggretating tensors

In [54]:
#create new tensor
tensor_3 = tf.constant([-2,-3,-9.5])

In [55]:
#get the absolute values
tf.abs(tensor_3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2. , 3. , 9.5], dtype=float32)>

In [56]:
tf.argmin(tensor_3,axis=0)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [57]:
tensor_3

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-2. , -3. , -9.5], dtype=float32)>

### Let's go with the different versions of aggregation functions:
* Get the max of tensor
* Get the min of tensor
* Get the mean of tensor
* Get the sum of tensor


In [58]:
#create new tensor:
tensor_4 = tf.constant([[1,2,3],[-1,-2,-3]])
#different versions of aggregations
print(f"The Maximum of Tensor: {tf.reduce_max(tensor_4)}")
print(f"The Minimum of Tensor: {tf.reduce_min(tensor_4)}")
print(f"The Sum of Tensor: {tf.add_n(tensor_4)}")
print(f"The Mean of Tensor: {tf.math.reduce_mean(tensor_4)}")

The Maximum of Tensor: 3
The Minimum of Tensor: -3
The Sum of Tensor: [0 0 0]
The Mean of Tensor: 0


💡 **Exercise**: Find the Variance and Standart Deviation of `tensor_4` tensor using Tensorflow methods.

### Getting Standart Deviation and Variance

In [59]:
#print tensor_4
print(tensor_4)
#let's change the type of tensor
tensor_4 = tf.cast(tensor_4,dtype = tf.float32) #our tensor must be real or complex after gettting variance and std
print('\n')
#get the variance and standart deviation
print(f"Variance of our tensor: {tf.math.reduce_variance(tensor_4)}")
print(f"Standart Deviation of our tensor: {tf.math.reduce_std(tensor_4)}")

tf.Tensor(
[[ 1  2  3]
 [-1 -2 -3]], shape=(2, 3), dtype=int32)


Variance of our tensor: 4.666666507720947
Standart Deviation of our tensor: 2.1602468490600586


In [60]:
#another example to get variance and standart deviation
import tensorflow_probability as tfp
#get the variance and standart deviation
print(f"Variance of our tensor: {tfp.stats.variance(tensor_4)}")
print(f"Standart Deviation of our tensor: {tfp.stats.stddev(tensor_4)}")

Variance of our tensor: [1. 4. 9.]
Standart Deviation of our tensor: [1. 2. 3.]


### Find the positional maximum and minimum

In [61]:
#create new tensor
tf.random.set_seed(42)
tensor_5 = tf.random.normal(shape = [50])
tensor_5

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
       -1.5066116 , -0.2645474 , -0.59722406, -1.9171132 , -0.62044144,
        0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
       -0.22561555, -0.7616443 , -1.8917141 , -0.93847126,  0.77852213,
       -0.47338897,  0.97772694,  0.24694404,  0.20573747, -0.5256233 ,
        0.32410017,  0.02545409, -0.10638497, -0.6369475 ,  1.1603122 ,
        0.2507359 , -0.41728503,  0.4012578 , -1.4145443 , -0.5931857 ,
       -1.6617213 ,  0.33567193,  0.10815629,  0.23479682, -0.56668764,
       -0.35819843,  0.88698614,  0.52744764,  0.70402247, -0.33421248],
      dtype=float32)>

In [62]:
#find the max value by index
tf.argmax(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [63]:
#find the maximum value of tensor with argmax
tensor_5[tf.argmax(tensor_5)]

<tf.Tensor: shape=(), dtype=float32, numpy=1.6994323>

In [64]:
#with reduce_max()
print(tf.reduce_max(tensor_5))
#check for the equality for the safety
tf.reduce_max(tensor_5) == tensor_5[tf.argmax(tensor_5)]

tf.Tensor(1.6994323, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [65]:
#find the position of min
tf.argmin(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [66]:
#find the min value by index
tensor_5[tf.argmin(tensor_5)]

<tf.Tensor: shape=(), dtype=float32, numpy=-3.0258412>

### Squeezing a tensor
Removing all single dimensions

In [68]:
#create a tensor to get started which has single dimensions
tf.random.set_seed(42)
tensor_6 = tf.constant(tf.random.uniform(shape = [50]),shape = [1,1,1,1,50])
tensor_6

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [69]:
tensor_6.shape

TensorShape([1, 1, 1, 1, 50])

In [71]:
squeezed_tensor = tf.squeeze(tensor_6)
squeezed_tensor,squeezed_tensor.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot Encoding Tensors

In [74]:
#create list of indices
our_list = [1,2,3,4,5]  #can be blue,red,green,purple,pink
#one hot encode
tf.one_hot(our_list,depth = 5) #shape is gonna be (5,5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [78]:
#specify custom values for one hot encoding
tf.one_hot(our_list,depth = 5,on_value = 'I love Artificial Intelligence',off_value = 'NLP is the favorite one')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'NLP is the favorite one', b'I love Artificial Intelligence',
        b'NLP is the favorite one', b'NLP is the favorite one',
        b'NLP is the favorite one'],
       [b'NLP is the favorite one', b'NLP is the favorite one',
        b'I love Artificial Intelligence', b'NLP is the favorite one',
        b'NLP is the favorite one'],
       [b'NLP is the favorite one', b'NLP is the favorite one',
        b'NLP is the favorite one', b'I love Artificial Intelligence',
        b'NLP is the favorite one'],
       [b'NLP is the favorite one', b'NLP is the favorite one',
        b'NLP is the favorite one', b'NLP is the favorite one',
        b'I love Artificial Intelligence'],
       [b'NLP is the favorite one', b'NLP is the favorite one',
        b'NLP is the favorite one', b'NLP is the favorite one',
        b'NLP is the favorite one']], dtype=object)>

### Squaring, log, square root

In [80]:
#create new tensor
tensor_7 = tf.range(1,15)
tensor_7

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)>

In [81]:
#square a tensor
tf.square(tensor_7)

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196], dtype=int32)>

In [84]:
#log on a tensor
tf.math.log(tf.cast(tensor_7,dtype = tf.float16)) #dtype must be float

<tf.Tensor: shape=(14,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 , 2.303 , 2.398 , 2.484 , 2.564 , 2.639 ], dtype=float16)>

In [83]:
#find the square root
tf.sqrt(tf.cast(tensor_7,dtype = tf.float32)) #dtype must be float

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166246, 3.4641016,
       3.6055512, 3.7416573], dtype=float32)>

### Finding access to GPUs

In [85]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [88]:
tf.config.list_physical_devices("GPU") #if this code return empty list when you check for the access for GPU,
#you have to change the runtime type from the None to the GPU. 

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [90]:
!nvidia-smi

Mon Jun 12 10:20:14 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    29W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------