<a href="https://colab.research.google.com/github/hasanzeynal/Tensorflow-Developer-Certificate/blob/main/TensorFlow%20Fundamentals/00%20-%20tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# We are gonna cover some fundamentals of using tensor in Tensorflow.
More specifically:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular python function)
* Using GPU's in tensorflow(or TPU's)
* Exercises

## Introduction to Tensors

In [1]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#create tensors with tf.constant
scalar = tf.constant(11)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [3]:
#check the type of tensor
scalar.dtype

tf.int32

In [4]:
#check the number fo dimentions of tensor
scalar.ndim

0

In [5]:
#creating vector
vector = tf.constant([10,20,30])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [6]:
#check the number of dimension of vector
vector.ndim

1

In [7]:
#create a matrix(has mor than 1 dimension)
matrix = tf.constant([[11,8],
                     [8,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 8, 11]], dtype=int32)>

In [8]:
#check for the number of dimensions
matrix.ndim

2

In [9]:
#create another matrix
another_matrix = tf.constant([[1, 2, 3],
                             [1, 2, 3],
                             [1, 2, 3]],dtype = tf.float16) #specify dtype of tensor
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float16)>

In [10]:
#creating 3 dimensinal matrix
threed_dimen = tf.constant([[[11,8],[1,2]],
                            [[8,11],[1,2]],
                            [[11,2],[1,2]]])
threed_dimen

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[11,  8],
        [ 1,  2]],

       [[ 8, 11],
        [ 1,  2]],

       [[11,  2],
        [ 1,  2]]], dtype=int32)>

In [11]:
#check for the number of dimentions
threed_dimen.ndim

3

In [12]:
#creat 4 dimensinal matrix
four_dimen = tf.constant([[[[1,2,3],[1,2,3]],
                          [[1,2,3],[1,2,3]]],
                          [[[1,2,3],[1,2,3]],
                          [[1,2,3],[1,2,3]]]])
four_dimen

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int32)>

In [13]:
four_dimen.ndim

4

## What we have learned so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: 2 dimensional array
* Tensor: n dimensional array(n can be any number, o dimensinal is a scalar, 1 dimensional is a vector)

### Creating Tensor with tf.Variable()

In [14]:
#create same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([1,2,3,4])
unchangeable_tensor = tf.constant([1,2,3,4])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>)

In [15]:
#Let's try to change changeable_tensor
changeable_tensor[1] = 4
changeable_tensor

TypeError: ignored

In [16]:
#What about .assign()?
changeable_tensor[3].assign(7)
changeable_tensor
#constant doesn't have .assign() function

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 7], dtype=int32)>

### Creating random tensors

In [17]:
#create 2 tensors
tensor_1 = tf.random.Generator.from_seed(45) # set seed for reproducibility
tensor_1 = tensor_1.uniform(shape=(3,2))
tensor_2 = tf.random.Generator.from_seed(45) 
tensor_2 = tensor_2.uniform(shape=(3,2))
tensor_1, tensor_2, tensor_1 == tensor_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.86540747, 0.8862978 ],
        [0.27795732, 0.8857763 ],
        [0.2179842 , 0.29115117]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.86540747, 0.8862978 ],
        [0.27795732, 0.8857763 ],
        [0.2179842 , 0.29115117]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [18]:
#Let's use tf.random.shuffle() to shuffle our tensor
not_shuffled = tf.constant([1,2,3,4,5])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 4, 5, 3, 2], dtype=int32)>

In [19]:
#Let's look at the 2 dimensional tensor
not_shuffled = tf.constant([[1,2,3,4,5],[6,7,8,9,10]])
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled,shuffled

(<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5]], dtype=int32)>)

In [20]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled,seed = 42) # operation level random seed


<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]], dtype=int32)>

### Other Ways to Create Tensors

In [21]:
#create tensor of all ones
tf.ones(shape = (3,6))

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
#create tensor of all zeroes
tf.zeros(shape = (4,5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into Tensors
The main difference between NumPy arrays and TensorFlow Tensors is tensors can run on the GPU(way much faster for numerical computing)

In [23]:
#creating numpy array
import numpy as np
numpy_array = np.arange(1,25,dtype = np.int32) #create NumPy array between 1 and 25
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
#turn into tensor
tensor_1 = tf.constant(numpy_array)
#change shape of tensor
tensor_2 = tf.constant(numpy_array,shape = (2,3,4)) # 2*3*4 = 24
tensor_1,tensor_2

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Getting Information from Tensors.
When dealing with tensors, you probably wanna be aware of following attributes:
* Shape
* Rank
* Axis or Dimension
* Size

In [25]:
#create rank 4 tensor(4 dimensional)
rank4_tensor = tf.ones(shape = (2,2,3,4))
rank4_tensor

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [26]:
#looking for shape,rank and size of rank4_tensor
rank4_tensor.shape,rank4_tensor.ndim,tf.size(rank4_tensor)

(TensorShape([2, 2, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=48>)

Let's look at previous example:
* Shape - Shape of Tensor
* Rank - Number of Dimensions
* Size - Total Number of Elements in the Tensor

### Indexing
Tensors can be indexed like Python Lists or NumPy Arrays

In [27]:
# Get the first 2 elements if each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [28]:
#Get the first element from each dimension from each index except final dimension
rank4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>

In [29]:
#create rank 2 tensor
rank_2_tensor = tf.constant([[1,2,3,4,5],[6,7,8,9,10]])
rank_2_tensor

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [30]:
#get the last item of each of row of  our rank tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 10], dtype=int32)>

In [31]:
# add in extra dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 5, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]], dtype=int32)>

In [32]:
#Alternative to the tf.newaxis
tf.expand_dims(rank_2_tensor,axis = -1)

<tf.Tensor: shape=(2, 5, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]], dtype=int32)>

In [33]:
#adding di,ension to the first axis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]], dtype=int32)>

In [34]:
#adding di,ension to the middle
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]], dtype=int32)>

In [35]:
#lookig for some attributes in the tensor
print("The Shape of Tensor:",tf.expand_dims(rank_2_tensor,axis=1).shape)
print("The Number of Dimensions:",tf.expand_dims(rank_2_tensor,axis=1).ndim)
print("The total number of elements:",tf.size(tf.expand_dims(rank_2_tensor,axis=1)))

The Shape of Tensor: (2, 1, 5)
The Number of Dimensions: 3
The total number of elements: tf.Tensor(10, shape=(), dtype=int32)


### Manupulating tensors(tensor operations)
**Basic Operations**





In [36]:
#addition
tensor = tf.constant([[10,20],[30,40]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [37]:
# Original tensor is not changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [38]:
#multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]], dtype=int32)>

In [39]:
#subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 10],
       [20, 30]], dtype=int32)>

### Matrix *Multiplication*

  In machine Learning, Matrix multiplication is one of the most usefull and important operation.
 
  There are 2 rules to multiply our tensors(or matrices):

1. The inner dimensions must match.
2. The resulting matrix has the shape of outher dimensions.

In [41]:
#matrix multiplication in tensowflow
print(tensor)
tf.linalg.matmul(tensor,tensor)

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 700, 1000],
       [1500, 2200]], dtype=int32)>

In [44]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 100,  400],
       [ 900, 1600]], dtype=int32)>

In [51]:
#Task: create tensor with shape of (3,3) and shape of (3,2)
tensor_1 = tf.constant([[1,4,5],
                        [1,2,5],
                        [1,5,9]])

tensor_2 = tf.constant([[1,2],
                        [8,9],
                        [5,6]])

In [53]:
# then multiply them with a Python operation
tensor_1 @ tensor_2 #"@" in Python for the Matrix Multiplication

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 58,  68],
       [ 42,  50],
       [ 86, 101]], dtype=int32)>

In [54]:
#let's do that with tf.matmul
tf.linalg.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 58,  68],
       [ 42,  50],
       [ 86, 101]], dtype=int32)>

In [66]:
#let's create two tensor with the same shape
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7,6],
                [8,9],
                [4,5]])
#let's try to multiply them
X @ y

InvalidArgumentError: ignored

In [67]:
#let's change the shape of y and try again
X @ tf.reshape(y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 14, 18],
       [57, 34, 44],
       [89, 54, 70]], dtype=int32)>

In [68]:
#now,reshape the X and we cann see that works or not
tf.reshape(X,shape = (2,3)) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 39],
       [92, 99]], dtype=int32)>

In [74]:
#Let's see the difference between tf.transpose() and tf,reshape() 
X,tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [71]:
#can do same thing with tf.transpose()
tf.transpose(X) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 58],
       [70, 78]], dtype=int32)>

In [72]:
#transpose y instead of X
tf.linalg.matmul(X,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 26, 14],
       [45, 60, 32],
       [71, 94, 50]], dtype=int32)>

📖 **Resource**: Info and Example of Matrix Multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html