<a href="https://colab.research.google.com/github/hasanzeynal/Tensorflow-Developer-Certificate/blob/main/TensorFlow%20Fundamentals/00-tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# We are gonna cover some fundamentals of using tensor in Tensorflow.
More specifically:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular python function)
* Using GPU's in tensorflow(or TPU's)
* Exercises

## Introduction to Tensors

In [1]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#create tensors with tf.constant
scalar = tf.constant(11)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [3]:
#check the type of tensor
scalar.dtype

tf.int32

In [18]:
#check the number fo dimentions of tensor
scalar.ndim

0

In [19]:
#creating vector
vector = tf.constant([10,20,30])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [20]:
#check the number of dimension of vector
vector.ndim

1

In [22]:
#create a matrix(has mor than 1 dimension)
matrix = tf.constant([[11,8],
                     [8,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 8, 11]], dtype=int32)>

In [23]:
#check for the number of dimensions
matrix.ndim

2

In [46]:
#create another matrix
another_matrix = tf.constant([[1, 2, 3],
                             [1, 2, 3],
                             [1, 2, 3]],dtype = tf.float16) #specify dtype of tensor
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float16)>

In [35]:
#creating 3 dimensinal matrix
threed_dimen = tf.constant([[[11,8],[1,2]],
                            [[8,11],[1,2]],
                            [[11,2],[1,2]]])
threed_dimen

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[11,  8],
        [ 1,  2]],

       [[ 8, 11],
        [ 1,  2]],

       [[11,  2],
        [ 1,  2]]], dtype=int32)>

In [36]:
#check for the number of dimentions
threed_dimen.ndim

3

In [42]:
#creat 4 dimensinal matrix
four_dimen = tf.constant([[[[1,2,3],[1,2,3]],
                          [[1,2,3],[1,2,3]]],
                          [[[1,2,3],[1,2,3]],
                          [[1,2,3],[1,2,3]]]])
four_dimen

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int32)>

In [40]:
four_dimen.ndim

4

## What we have learned so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: 2 dimensional array
* Tensor: n dimensional array(n can be any number, o dimensinal is a scalar, 1 dimensional is a vector)

### Creating Tensor with tf.Variable()

In [50]:
#create same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([1,2,3,4])
unchangeable_tensor = tf.constant([1,2,3,4])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>)

In [55]:
#Let's try to change changeable_tensor
changeable_tensor[1] = 4
changeable_tensor

TypeError: ignored

In [59]:
#What about .assign()?
changeable_tensor[3].assign(7)
changeable_tensor
#constant doesn't have .assign() function

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 7], dtype=int32)>

### Creating random tensors