<a href="https://colab.research.google.com/github/hasanzeynal/TensorFlow-Developer-Certificate/blob/main/Exercises/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🛠 00.TensorFlow Fundamentals Exercises

#### Exercise 1.
Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().


In [ ]:
#import tensorflow
import tensorflow as tf
#create scalar,vector,matrix and tensir
print(f"Scalar: {tf.constant(3)}") #number od dimension = 0
print(f"Vector: {tf.constant([1,2,4])}") #number od dimension = 1
print(f"Matrix: \n{tf.constant([[4,5,7],[4,7,9]])}") #number od dimension = 2
tensor = tf.constant([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #number od dimension = can be different shapes
print(f"Tensor: \n{tensor}")

Scalar: 3
Vector: [1 2 4]
Matrix: 
[[4 5 7]
 [4 7 9]]
Tensor: 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


📝 **Note**: The difference between Matrix and Tensor: Matrix onky can be 2 dimensional but Tensor cen be different shapes.You can think of a tensor as a higher-dimensional way to organize information. So a matrix (5x5 for example) is a tensor of rank 2.

#### Exercise 2.
Find the shape, rank and size of the tensors you created in 1.


In [ ]:
#get the shape,rank and size of tensor which is created in exercise 1
print("The Shape of Tensor: ",tensor.shape)
print("The Rank of Tensor: ",tensor.ndim) #rank means number of dimensions
print("The Size of Tensor: ",tf.size(tensor)) #size means total number of elements in tensor

The Shape of Tensor:  (2, 2, 4)
The Rank of Tensor:  3
The Size of Tensor:  tf.Tensor(16, shape=(), dtype=int32)


#### Exercise 3.
Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [ ]:
#create 2 tensors which is containg random values between 0 and 1
tensor_1 = tf.random.uniform(shape = [5,300],minval=0,maxval = 1)
tensor_2 = tf.random.uniform(shape = [5,300],minval=0,maxval = 1)

#### Exercise 4.
 Multiply the two tensors you created in 3 using matrix multiplication.


In [ ]:
#maltuplication using tf.matmul()
tf.matmul(tensor_1,tf.transpose(tensor_2)) #transpose to not getting error,remember the rules.

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.09271 , 76.764694, 76.62086 , 75.045334, 75.066154],
       [77.57048 , 81.38469 , 78.160904, 80.962494, 78.58233 ],
       [76.78978 , 85.83865 , 79.82314 , 83.47469 , 75.92397 ],
       [75.14124 , 78.880646, 74.57582 , 74.50623 , 71.56018 ],
       [76.04808 , 75.49192 , 74.94261 , 76.894394, 74.69604 ]],
      dtype=float32)>

#### Exercise 5.
Multiply the two tensors you created in 3 using dot product.


In [ ]:
#multiplication using tensordot
tf.tensordot(tensor_1,tf.transpose(tensor_2),axes = 1)#axes must be given

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.09271 , 76.764694, 76.62086 , 75.045334, 75.066154],
       [77.57048 , 81.38469 , 78.160904, 80.962494, 78.58233 ],
       [76.78978 , 85.83865 , 79.82314 , 83.47469 , 75.92397 ],
       [75.14124 , 78.880646, 74.57582 , 74.50623 , 71.56018 ],
       [76.04808 , 75.49192 , 74.94261 , 76.894394, 74.69604 ]],
      dtype=float32)>

#### Exercise 6.
Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
#crete a tensor
tensor_3 = tf.random.uniform(shape = [224,224,3],minval = 0,maxval = 1)
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.50076425, 0.2987175 , 0.8884711 ],
        [0.38392723, 0.43805695, 0.1862241 ],
        [0.69492567, 0.17708075, 0.16034675],
        ...,
        [0.9142219 , 0.14476812, 0.22889447],
        [0.31085742, 0.51891685, 0.44350207],
        [0.07689476, 0.8465502 , 0.6810421 ]],

       [[0.073632  , 0.08876634, 0.87733376],
        [0.7076491 , 0.14638889, 0.7326473 ],
        [0.66994715, 0.62114596, 0.12321007],
        ...,
        [0.09773254, 0.8056066 , 0.79563284],
        [0.20788419, 0.2382127 , 0.12442803],
        [0.35737312, 0.08532476, 0.48011696]],

       [[0.19844747, 0.31776786, 0.0850656 ],
        [0.49853826, 0.41695595, 0.03940558],
        [0.03244615, 0.6493677 , 0.2808193 ],
        ...,
        [0.8436475 , 0.23940611, 0.42089605],
        [0.5829694 , 0.23786592, 0.22571135],
        [0.37503088, 0.42606103, 0.0769583 ]],

       ...,

       [[0.6221365 , 0.19788599, 0.20065153],
        [0.96

#### Exercise 7.
 Find the min and max values of the tensor you created in 6 along the first axis.


In [ ]:
print("The Minimum value of tensor: ",tf.reduce_min(tensor_3))
print("The Maximum value of tensor: ",tf.reduce_max(tensor_3))

The Minimum value of tensor:  tf.Tensor(2.3841858e-07, shape=(), dtype=float32)
The Maximum value of tensor:  tf.Tensor(0.99999917, shape=(), dtype=float32)


####Exercise 8.
Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [ ]:
#creating tensor
tensor_4 = tf.random.uniform(shape = [1,224,224,3])
#loking for the shapes
tensor_4.shape,tf.squeeze(tensor_4).shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

#### Exercise 9.
 Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [ ]:
#create a tensor
tensor_4 = tf.constant([1,4,7,9,12,54,-5,8,9,91])
#let's get indix of max value
index_of_max = tf.argmax(tensor_4)
print("The Index of Max Value: ",index_of_max)
#getting max value using index
print("The Max Value: ",tensor_4[index_of_max])

The Index of Max Value:  tf.Tensor(9, shape=(), dtype=int64)
The Max Value:  tf.Tensor(91, shape=(), dtype=int32)


####Exercise 10.
 One-hot encode the tensor you created in 9.

In [ ]:
#one-hot encoding on tensor_4
tf.one_hot(tensor_4,depth = 10) #depth must be given to not get error

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>